- name: UFW - Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: UFW - Allow SSH on port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: UFW - Allow HTTP on port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: UFW - Allow HTTPS on port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW
  ufw:
    state: enabled
